const single = [['你','nǐ'],['好','hǎo'],['我','wǒ'],['的','de'],['名','míng'],['字','zì'],['叫','jiào'],['什','shén'],['麼','me']];
const number = [['一','yī'],['二','èr'],['三','sān'],['四','sì'],['五','wǔ'],['六','liù'],['七','qī'],['八','bā'],['九','jiǔ'],['十','shí']];
const word = [['你好','nǐ hǎo'],['我的','wǒ de'],['名字','míng zi'],['什麼','shén me']];
const banks = { single, word, number, all: [...single, ...word, ...number] };
const audioMap = Object.fromEntries([...single, ...number, ...word].map(([text], index) => [text, `Audio/csl2_rolling-${String(index + 1).padStart(4, '0')}.mp3`]));
const names = { all: '全部', single: '單生字', word: '雙字詞語', number: '🔢 數字' };
let mode = 'all', last = '', busy = false, showPinyin = true, currentPinyin = '', currentQuestion = '', audioContext = null, currentAudio = null;
const ball = document.querySelector('#ball'), ballText = document.querySelector('#ballText'), cn = document.querySelector('#cn'), py = document.querySelector('#py'), go = document.querySelector('#go'), label = document.querySelector('#label'), count = document.querySelector('#count'), toggle = document.querySelector('#toggle');

function updateUI() { label.textContent = `目前題庫：${names[mode]}`; count.textContent = `題庫共 ${banks[mode].length} 題`; document.querySelectorAll('.mode').forEach(button => button.classList.toggle('active', button.dataset.mode === mode)); }
function pickQuestion() { const bank = banks[mode]; let item = bank[Math.floor(Math.random() * bank.length)], attempts = 0; while (item[0] === last && bank.length > 1 && attempts++ < 20) item = bank[Math.floor(Math.random() * bank.length)]; last = item[0]; return item; }
function playSpinSound() { try { const AudioContextClass = window.AudioContext || window.webkitAudioContext; if (!AudioContextClass) return; audioContext ||= new AudioContextClass(); audioContext.resume(); const now = audioContext.currentTime; for (let i = 0; i < 4; i++) { const oscillator = audioContext.createOscillator(), gain = audioContext.createGain(), start = now + i * .09; oscillator.type = 'sine'; oscillator.frequency.setValueAtTime(440 + i * 90, start); gain.gain.setValueAtTime(.0001, start); gain.gain.exponentialRampToValueAtTime(.08, start + .015); gain.gain.exponentialRampToValueAtTime(.0001, start + .12); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(start); oscillator.stop(start + .13); } } catch (_) {} }
function browserSpeak(text) { if (!window.speechSynthesis || !window.SpeechSynthesisUtterance) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'zh-TW'; utterance.rate = .82; const voices = window.speechSynthesis.getVoices(); utterance.voice = voices.find(voice => voice.lang.toLowerCase() === 'zh-tw') || voices.find(voice => voice.lang.toLowerCase().startsWith('zh')) || null; window.speechSynthesis.speak(utterance); }
function stopQuestionAudio() { if (currentAudio) { currentAudio.pause(); currentAudio.currentTime = 0; currentAudio = null; } window.speechSynthesis?.cancel(); }
function speakQuestion() { if (!currentQuestion) return; stopQuestionAudio(); const text = currentQuestion, source = audioMap[text]; if (!source) return browserSpeak(text); const audio = new Audio(`${source}?v=20260920-2`); audio.preload = 'auto'; audio.volume = 1; currentAudio = audio; let fallbackUsed = false; const fallback = () => { if (fallbackUsed) return; fallbackUsed = true; if (currentAudio === audio) currentAudio = null; browserSpeak(text); }; audio.addEventListener('ended', () => { if (currentAudio === audio) currentAudio = null; }, { once: true }); audio.addEventListener('error', fallback, { once: true }); audio.play().catch(fallback); }
function spin() { if (busy) return; busy = true; stopQuestionAudio(); currentQuestion = ''; go.disabled = true; playSpinSound(); cn.textContent = '轉～轉～轉～'; py.textContent = showPinyin ? '會抽到哪一個呢？' : ''; ballText.textContent = '？'; ball.classList.remove('spin'); void ball.offsetWidth; ball.classList.add('spin'); const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; setTimeout(() => { const item = pickQuestion(); [currentQuestion, currentPinyin] = item; ballText.textContent = currentQuestion; cn.textContent = currentQuestion; py.textContent = showPinyin ? currentPinyin : ''; ball.classList.remove('spin'); busy = false; go.disabled = false; }, reducedMotion ? 180 : 1550); }

ball.addEventListener('click', spin); go.addEventListener('click', speakQuestion);
document.querySelectorAll('.mode').forEach(button => button.addEventListener('click', () => { if (busy) return; mode = button.dataset.mode; last = ''; currentQuestion = ''; currentPinyin = ''; stopQuestionAudio(); go.disabled = true; ballText.textContent = '？'; cn.textContent = names[mode]; py.textContent = showPinyin ? '點球開始抽題！' : ''; updateUI(); }));
toggle.addEventListener('click', () => { showPinyin = !showPinyin; toggle.textContent = showPinyin ? '🙈 隱藏拼音' : '👀 顯示拼音'; py.textContent = showPinyin ? (currentPinyin || '點球開始！') : ''; });
updateUI();
